language: c++
dist: trusty
sudo: false
matrix:
  include:
  # Linux Debug GCC
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="BUILD_CONFIG=debug && OUTPUT_FOLDER=bin_linux"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
            - gcovr
      before_script:
        - tools/premake/premake5 gmake --coverage
      after_script:
        - bash <(curl -s https://codecov.io/bash)
  # Linux Release GCC
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="BUILD_CONFIG=release && OUTPUT_FOLDER=bin_linux"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
      before_script:
        - tools/premake/premake5 gmake
  # Linux Debug Clang
    - os: linux
      compiler: clang
      env:
        - MATRIX_EVAL="BUILD_CONFIG=debug && OUTPUT_FOLDER=bin_linux"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
      before_script:
        - tools/premake/premake5 gmake --cc=clang
  # Linux Release Clang
    - os: linux
      compiler: clang
      env:
        - MATRIX_EVAL="BUILD_CONFIG=release && OUTPUT_FOLDER=bin_linux"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
      before_script:
        - tools/premake/premake5 gmake --cc=clang
  # macOS Debug
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="BUILD_CONFIG=debug && OUTPUT_FOLDER=bin_macosx"
      before_script:
        - brew update
        - brew install sdl2
        - tools/premake/premake5-osx gmake
  # macOS Debug
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="BUILD_CONFIG=release && OUTPUT_FOLDER=bin_macosx"
      before_script:
        - brew update
        - brew install sdl2
        - tools/premake/premake5-osx gmake

script:
 - eval "${MATRIX_EVAL}"
 - make -j4 config=${BUILD_CONFIG}_x64
 - builds/${OUTPUT_FOLDER}/lorcoretests