language: c++
dist: trusty
sudo: false
matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="PREMAKE_BINARY=premake5 && PREMAKE_ACTION=gmake && PREMAKE_OPTIONS=--coverage && BUILD_CONFIG=debug && OUTPUT_FOLDER=bin_linux"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
            - gcovr
      after_script:
        - gcovr -r .
        - bash <(curl -s https://codecov.io/bash)
    - os: linux
      compiler: gcc
      env:
        - MATRIX_EVAL="PREMAKE_BINARY=premake5 && PREMAKE_ACTION=gmake && BUILD_CONFIG=release && OUTPUT_FOLDER=bin_linux"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
    - os: linux
      compiler: clang
      env:
        - MATRIX_EVAL="PREMAKE_BINARY=premake5 && PREMAKE_ACTION=gmake && PREMAKE_OPTIONS=--cc=clang && BUILD_CONFIG=debug && OUTPUT_FOLDER=bin_linux"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
    - os: linux
      compiler: clang
      env:
        - MATRIX_EVAL="PREMAKE_BINARY=premake5 && PREMAKE_ACTION=gmake && PREMAKE_OPTIONS=--cc=clang && BUILD_CONFIG=release && OUTPUT_FOLDER=bin_linux"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="brew update && brew install sdl2 && PREMAKE_BINARY=premake5-osx && PREMAKE_ACTION=gmake && BUILD_CONFIG=debug && OUTPUT_FOLDER=bin_macosx"
    - os: osx
      osx_image: xcode9
      env:
        - MATRIX_EVAL="brew update && brew install sdl2 && PREMAKE_BINARY=premake5-osx && PREMAKE_ACTION=gmake && BUILD_CONFIG=release && OUTPUT_FOLDER=bin_macosx"

script:
 - eval "${MATRIX_EVAL}"
 - tools/premake/${PREMAKE_BINARY} ${PREMAKE_ACTION} ${PREMAKE_OPTIONS}
 - make -j4 config=${BUILD_CONFIG}_x64
 - builds/${OUTPUT_FOLDER}/lorcoretests