language: c++
dist: trusty
sudo: false
matrix:
  include:
  # Linux Debug GCC
    - os: linux
      compiler: gcc
      env:
        - BUILD_INFO="Linux-Debug-GCC"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
            - gcovr
      before_script:
        - tools/premake/premake5 gmake --coverage
      script:
        - make -j4 config=debug_x64
        - builds/bin_linux/lorcoretests
      after_script:
        - bash <(curl -s https://codecov.io/bash)
  # Linux Release GCC
    - os: linux
      compiler: gcc
      env:
        - BUILD_INFO="Linux-Release-GCC"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
      before_script:
        - tools/premake/premake5 gmake
      script:
        - make -j4 config=release_x64
        - builds/bin_linux/lorcoretests
  # Linux Debug Clang
    - os: linux
      compiler: clang
      env:
        - BUILD_INFO="Linux-Debug-Clang"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
      before_script:
        - tools/premake/premake5 gmake --cc=clang
      script:
        - make -j4 config=debug_x64
        - builds/bin_linux/lorcoretests
  # Linux Release Clang
    - os: linux
      compiler: clang
      env:
        - BUILD_INFO="Linux-Release-Clang"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libsdl2-dev
      before_script:
        - tools/premake/premake5 gmake --cc=clang
      script:
        - make -j4 config=release_x64
        - builds/bin_linux/lorcoretests
  # macOS Debug
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_INFO="macOS-Debug"
      before_script:
        - brew update
        - brew install sdl2
        - tools/premake/premake5-osx gmake
      script:
        - make -j4 config=debug_x64
        - builds/bin_macosx/lorcoretests
  # macOS Release
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_INFO="macOS-Release"
      before_script:
        - brew update
        - brew install sdl2
        - tools/premake/premake5-osx gmake
      script:
        - make -j4 config=release_x64
        - builds/bin_macosx/lorcoretests
  # iOS Debug
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_INFO="iOS-Debug"
      before_script:
        - tools/premake/premake5-osx xcode4 --system=ios
      script:
        - xcodebuild -project tests/lorcoretests.xcodeproj -configuration Debug -arch x86_64 -sdk iphonesimulator
  # iOS Release
    - os: osx
      osx_image: xcode9
      env:
        - BUILD_INFO="iOS-Release"
      before_script:
        - tools/premake/premake5-osx xcode4 --system=ios
      script:
        - xcodebuild -project tests/lorcoretests.xcodeproj -configuration Release -arch x86_64 -sdk iphonesimulator
